CREATE TABLE movies(
    ID INT NOT NULL,
    TITLE VARCHAR(30) NOT NULL,
    RELEASE_DATE DATE,
    DURATION INT,
    SCORE INT,
    PRIMARY KEY(ID)
);

CREATE TABLE genres(
    ID INT NOT NULL,
    NAME VARCHAR(25) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE movie_genre (
    ID_MOVIE INT NOT NULL,
    ID_GENRE INT NOT NULL,
    CONSTRAINT fk_movie_id FOREIGN KEY (ID_MOVIE) REFERENCES movies(ID),
    CONSTRAINT fk_genre_id FOREIGN KEY (ID_GENRE) REFERENCES genres(ID)
);